import "./globals.css";
import Link from "next/link";

import Navigation from "./components/nav"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <div>{children}</div>
      </body>
    </html>
  );
}

